[BUGFIX] Do not declare "strict_types" in ext_* files
Because of configuration file concatenation this would lead to errors
like this:

Fatal error: strict_types declaration must be the very first statement
in the script